export const SERVICE_KEYS = {
  DELIVERY_SERVICE: Symbol("DELIVERY_SERVICE"),
  DELIVERY_PACKAGE_SERVICE: Symbol("DELIVERY_PACKAGE_SERVICE"),
  PATH_SERVICE: Symbol("PATH_SERVICE"),
  WAREHOUSE_SERVICE: Symbol("WAREHOUSE_SERVICE"),
  TRUCK_SERVICE: Symbol("TRUCK_SERVICE"),
  PLANNING_SERVICE: Symbol("PLANNING_SERVICE"),
  USER_SERVICE: Symbol("USER_SERVICE"),
  AUTH_SERVICE: Symbol("AUTH_SERVICE"),
  TRIP_SERVICE: Symbol("TRIP_SERVICE"),
};
